from flask import Flask, request, render_template, Response
import yt_dlp
import re
import unicodedata
import browser_cookie3  # Çerezleri almak için
import tempfile         # Geçici dosya oluşturmak için
import os
from urllib.parse import quote  # Unicode karakterler için encode işlemi

app = Flask(__name__)

@app.route('/')
def index():
    # Ana arama ve indirme sayfasını gösterir
    return render_template('index.html')

@app.route('/process', methods=['GET'])
def process():
    query = request.args.get('query')
    if not query:
        return "No input provided", 400

    # Kullanıcının bir YouTube linki mi yoksa arama sorgusu mu girdiğini kontrol et
    if "youtube.com" in query or "youtu.be" in query:
        # Kullanıcı bir link yapıştırdıysa, doğrudan indirme işlemini başlat
        return download_video(query)
    else:
        # Kullanıcı bir arama sorgusu girdi; arama sonuçlarını getir
        return search_videos(query)

def get_cookiefile():
    """browser_cookie3 çerezlerini Netscape formatına dönüştürüp geçici dosyaya kaydeder."""
    cookies = browser_cookie3.firefox(domain_name="youtube.com")  # Firefox
    # Eğer Chrome kullanıyorsanız, aşağıdaki satırı kullanabilirsiniz:
    # cookies = browser_cookie3.chrome(domain_name="youtube.com")

    # Netscape formatında çerez dosyası oluştur
    temp_cookiefile = tempfile.NamedTemporaryFile(delete=False, suffix=".txt")
    with open(temp_cookiefile.name, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file is generated by browser_cookie3\n\n")
        for cookie in cookies:
            f.write(
                f"{cookie.domain}\t"
                f"{'TRUE' if cookie.domain.startswith('.') else 'FALSE'}\t"
                f"{cookie.path}\t"
                f"{'TRUE' if cookie.secure else 'FALSE'}\t"
                f"{int(cookie.expires) if cookie.expires else 0}\t"
                f"{cookie.name}\t"
                f"{cookie.value}\n"
            )
    return temp_cookiefile.name

def search_videos(query):
    try:
        cookiefile = get_cookiefile()
        ydl_opts = {
            'quiet': True,
            'extract_flat': True,  # Sadece listelemek için kullanılıyor
            'cookiefile': cookiefile
        }

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            search_results = ydl.extract_info(f"ytsearch10:{query}", download=False)

        # Sonuçları işleme
        videos = [
            {
                'id': entry['id'],
                'title': entry['title'],
                'url': f"https://www.youtube.com/watch?v={entry['id']}"
            }
            for entry in search_results.get('entries', [])
        ]

        return render_template('search_results.html', videos=videos)

    except Exception as e:
        return f"Error: {str(e)}", 500

def generate_file(downloaded_file, output_dir):
    """
    Dosyayı chunk'lar halinde (64 KB) okuyup gönderir.
    İşlem bittikten sonra dosya ve klasör otomatik silinir.
    """
    try:
        with open(downloaded_file, 'rb') as f:
            while True:
                chunk = f.read(64 * 1024)
                if not chunk:
                    break
                yield chunk
    finally:
        # Akış sonlandığında geçici dosyaları ve klasörü sil
        if os.path.exists(downloaded_file):
            os.remove(downloaded_file)
        if os.path.exists(output_dir):
            os.rmdir(output_dir)

def download_video(video_url):
    output_dir = None
    try:
        cookiefile = get_cookiefile()
        output_dir = tempfile.mkdtemp()  # Geçici bir klasör oluştur
        ydl_opts = {
            'format': 'bestaudio/best',
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': '192',
            }],
            'cookiefile': cookiefile,
            'outtmpl': os.path.join(output_dir, '%(title)s.%(ext)s'),
        }

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            result = ydl.extract_info(video_url, download=True)
            video_title = result.get('title', 'audio')
            downloaded_file = ydl.prepare_filename(result)
            # Eğer uzantıyı elle değiştirmek gerekiyorsa:
            # downloaded_file = downloaded_file.replace('.webm', '.mp3').replace('.m4a', '.mp3')

        # Güvenli dosya adı oluştur (Unicode sorunlarına karşı)
        sanitized_title = re.sub(r'[^\w\s-]', '', unicodedata.normalize('NFKD', video_title))\
            .strip().replace(' ', '_')
        encoded_filename = quote(f"{sanitized_title}.mp3")

        return Response(
            generate_file(downloaded_file, output_dir),
            content_type='audio/mpeg',
            headers={
                'Content-Disposition': f"attachment; filename*=UTF-8''{encoded_filename}",
                'Cache-Control': 'no-cache',  # İsteğe bağlı
            },
        )

    except Exception as e:
        # İndirme veya hazırlık sırasında hata olursa geçici dosyaları temizle
        if output_dir and os.path.exists(output_dir):
            for file in os.listdir(output_dir):
                os.remove(os.path.join(output_dir, file))
            os.rmdir(output_dir)
        return f"Error: {str(e)}", 500

if __name__ == '__main__':
    # Uygulamayı çalıştır
    app.run(host='0.0.0.0', port='5000', debug=True, threaded=True)
